version: '3.7'
services:
  db:
    image: postgres:16
    container_name: db_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app

  app:
    build: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ['/fastapi_app/docker/app.sh']
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ['/fastapi_app/docker/celery-flower.sh', 'celery']
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: ['/fastapi_app/docker/celery-flower.sh', 'flower']
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
volumes:
  pgdata: