version: '3.7'
services:
  db:
    image: postgres:16
    container_name: db_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: bash -c "alembic upgrade head && gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: bash -c "celery --app=src.tasks.tasks:celery worker"
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: bash -c "celery --app=src.tasks.tasks:celery flower"
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555
volumes:
  pgdata: